<a href="https://colab.research.google.com/github/maryofcarmo/ICV/blob/main/LIMPEZA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1° Ligar ao google e chamar bibliotecas necessárias

In [1]:
# conecta o notebook ao google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# inicia chamando todas as bibliotecas necessárias
import pandas as pd
import os
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point

# 2° Leitura dos arquivos e colocar todos em um dicionário

In [3]:
# Defina o diretório onde estão os arquivos CSV
diretorio = '/content/drive/MyDrive/TCC/DADOS/CONVENCIONAL'

# Obtenha a lista de todos os arquivos CSV no diretório
arquivos_csv = [f for f in os.listdir(diretorio) if f.endswith('.csv')]

arquivos_csv

['Nome:_AGUA_BRANCA_Codigo_Estacao:_82989.csv',
 'Nome:_ARAPIRACA_Codigo_Estacao:_82995.csv',
 'Nome:_MACEIO_Codigo_Estacao:_82994.csv',
 'Nome:_MAJOR_ISIDORO_Codigo_Estacao:_82991.csv',
 'Nome:_MATA_GRANDE_Codigo_Estacao:_82988.csv',
 'Nome:_PALMEIRA_DOS_INDIOS_Codigo_Estacao:_82992.csv',
 'Nome:_PAO_DE_ACUCAR_Codigo_Estacao:_82990.csv',
 'Nome:_PILAR_(MANGUABA)_Codigo_Estacao:_82998.csv',
 'Nome:_PORTO_DE_PEDRAS_Codigo_Estacao:_82996.csv',
 'Nome:_ALAGOINHAS_Codigo_Estacao:_83249.csv',
 'Nome:_BARRA_Codigo_Estacao:_83179.csv',
 'Nome:_BARREIRAS_Codigo_Estacao:_83236.csv',
 'Nome:_BOM_JESUS_DA_LAPA_Codigo_Estacao:_83288.csv',
 'Nome:_CAETITE_Codigo_Estacao:_83339.csv',
 'Nome:_CAMACARI_Codigo_Estacao:_83226.csv',
 'Nome:_CANAVIEIRAS_Codigo_Estacao:_83398.csv',
 'Nome:_CARAVELAS_Codigo_Estacao:_83498.csv',
 'Nome:_CARINHANHA_Codigo_Estacao:_83408.csv',
 'Nome:_CIPO_Codigo_Estacao:_83192.csv',
 'Nome:_CORRENTINA_Codigo_Estacao:_83286.csv',
 'Nome:_CRUZ_DAS_ALMAS_Codigo_Estacao:_83222.csv',
 'Nome:_FEIRA_DE_SANTANA_Codigo_Estacao:_83221.csv',
 'Nome:_GUARATINGA_Codigo_Estacao:_83446.csv',
 'Nome:_IRECE_Codigo_Estacao:_83182.csv',
 'Nome:_ITABERABA_Codigo_Estacao:_83244.csv',
 'Nome:_ITABUNA_Codigo_Estacao:_83347.csv',
 'Nome:_ITIRUCU_(JAGUAQUARA)_Codigo_Estacao:_83295.csv',
 'Nome:_ITUACU_Codigo_Estacao:_83292.csv',
 'Nome:_JACOBINA_Codigo_Estacao:_83186.csv',
 'Nome:_LENCOIS_Codigo_Estacao:_83242.csv',
 'Nome:_MONTE_SANTO_Codigo_Estacao:_83090.csv',
 'Nome:_MORRO_DO_CHAPEU_Codigo_Estacao:_83184.csv',
 'Nome:_MUCURI_Codigo_Estacao:_83549.csv',
 'Nome:_PAULO_AFONSO_Codigo_Estacao:_82986.csv',
 'Nome:_REMANSO_Codigo_Estacao:_82979.csv',
 'Nome:_SALVADOR_(ONDINA)_Codigo_Estacao:_83229.csv',
 'Nome:_SENHOR_DO_BONFIM_Codigo_Estacao:_83088.csv',
 'Nome:_SERRINHA_Codigo_Estacao:_83190.csv',
 'Nome:_STa._R._DE_CASSIA_(IBIPETUBA)_Codigo_Estacao:_83076.csv',
 'Nome:_VITORIA_DA_CONQUISTA_Codigo_Estacao:_83344.csv',
 'Nome:_ACARAU_Codigo_Estacao:_82294.csv',
 'Nome:_BARBALHA_Codigo_Estacao:_82784.csv',
 'Nome:_CAMPOS_SALES_Codigo_Estacao:_82777.csv',
 'Nome:_CRATEUS_Codigo_Estacao:_82583.csv',
 'Nome:_FORTALEZA_Codigo_Estacao:_82397.csv',
 'Nome:_GUARAMIRANGA_Codigo_Estacao:_82487.csv',
 'Nome:_IGUATU_Codigo_Estacao:_82686.csv',
 'Nome:_JAGUARUANA_Codigo_Estacao:_82493.csv',
 'Nome:_JUAZEIRO_DO_NORTE_Codigo_Estacao:_82785.csv',
 'Nome:_MORADA_NOVA_Codigo_Estacao:_82588.csv',
 'Nome:_QUIXADA_Codigo_Estacao:_82486.csv',
 'Nome:_QUIXERAMOBIM_Codigo_Estacao:_82586.csv',
 'Nome:_SOBRAL_Codigo_Estacao:_82392.csv',
 'Nome:_TAUA_Codigo_Estacao:_82683.csv',
 'Nome:_VICOSA_DO_CEARA_Codigo_Estacao:_82390.csv',
 'Nome:_ALTO_PARNAIBA_Codigo_Estacao:_82970.csv',
 'Nome:_BACABAL_Codigo_Estacao:_82460.csv',
 'Nome:_BALSAS_Codigo_Estacao:_82768.csv',
 'Nome:_BARRA_DO_CORDA_Codigo_Estacao:_82571.csv',
 'Nome:_CAROLINA_Codigo_Estacao:_82765.csv',
 'Nome:_CAXIAS_Codigo_Estacao:_82476.csv',
 'Nome:_CHAPADINHA_Codigo_Estacao:_82382.csv',
 'Nome:_COLINAS_Codigo_Estacao:_82676.csv',
 'Nome:_IMPERATRIZ_Codigo_Estacao:_82564.csv',
 'Nome:_SAO_LUIS_Codigo_Estacao:_82280.csv',
 'Nome:_TURIACU_Codigo_Estacao:_82198.csv',
 'Nome:_ZE_DOCA_Codigo_Estacao:_82376.csv',
 'Nome:_AREIA_Codigo_Estacao:_82696.csv',
 'Nome:_CAMARATUBA_Codigo_Estacao:_82695.csv',
 'Nome:_CAMPINA_GRANDE_Codigo_Estacao:_82795.csv',
 'Nome:_GUARABIRA_Codigo_Estacao:_82697.csv',
 'Nome:_JOAO_PESSOA_Codigo_Estacao:_82798.csv',
 'Nome:_MONTEIRO_Codigo_Estacao:_82792.csv',
 'Nome:_PATOS_Codigo_Estacao:_82791.csv',
 'Nome:_SAO_GONCALO_Codigo_Estacao:_82689.csv',
 'Nome:_ARCO_VERDE_Codigo_Estacao:_82890.csv',
 'Nome:_CABROBO_Codigo_Estacao:_82886.csv',
 'Nome:_GARANHUNS_Codigo_Estacao:_82893.csv',
 'Nome:_GOIANA_Codigo_Estacao:_82799.csv',
 'Nome:_NAZARE_DA_MATA_Codigo_Estacao:_82781.csv',
 'Nome:_OLINDA_Codigo_Estacao:_82898.csv',
 'Nome:_OURICURI_Codigo_Estacao:_82753.csv',
 'Nome:_PESQUEIRA_Codigo_Estacao:_82892.csv',
 'Nome:_PETROLINA_Codigo_Estacao:_82983.csv',
 'Nome:_RECIFE_(CURADO)_Codigo_Estacao:_82900.csv',
 'Nome:_SURUBIM_Codigo_Estacao:_82797.csv',
 'Nome:_TAPACURA_Codigo_Estacao:_82897.csv',
 'Nome:_TRIUNFO_Codigo_Estacao:_82789.csv',
 'Nome:_ALTO_LONGA_(PILOTO_DO_LONGA)_Codigo_Estacao:_82605.csv',
 'Nome:_BOM_JESUS_DO_PIAUI_Codigo_Estacao:_82975.csv',
 'Nome:_CALDEIRAO_Codigo_Estacao:_82474.csv',
 'Nome:_CARACOL_Codigo_Estacao:_82976.csv',
 'Nome:_ESPERANTINA_Codigo_Estacao:_82298.csv',
 'Nome:_FLORIANO_Codigo_Estacao:_82678.csv',
 'Nome:_LUZILANDIA(LAG.DO_PIAUI)_Codigo_Estacao:_82296.csv',
 'Nome:_MORRO_DOS_CAVALOS_Codigo_Estacao:_82684.csv',
 'Nome:_PARNAIBA_Codigo_Estacao:_82287.csv',
 'Nome:_PAULISTANA_Codigo_Estacao:_82882.csv',
 'Nome:_PICOS_Codigo_Estacao:_82780.csv',
 'Nome:_PIRIPIRI_Codigo_Estacao:_82480.csv',
 'Nome:_SAO_JOAO_DO_PIAUI_Codigo_Estacao:_82879.csv',
 'Nome:_TERESINA_Codigo_Estacao:_82578.csv',
 'Nome:_VALE_DO_GURGUEIA_(CRISTIANO_CASTRO)_Codigo_Estacao:_82870.csv',
 'Nome:_APODI_Codigo_Estacao:_82590.csv',
 'Nome:_CEARA_MIRIM_Codigo_Estacao:_82596.csv',
 'Nome:_CRUZETA_Codigo_Estacao:_82693.csv',
 'Nome:_FLORANIA_Codigo_Estacao:_82691.csv',
 'Nome:_MACAIBA_Codigo_Estacao:_82597.csv',
 'Nome:_MACAU_Codigo_Estacao:_82594.csv',
 'Nome:_MOSSORO_Codigo_Estacao:_82591.csv',
 'Nome:_NATAL_Codigo_Estacao:_82598.csv',
 'Nome:_NOVA_CRUZ_Codigo_Estacao:_82698.csv',
 'Nome:_SERIDO_(CAICO)_Codigo_Estacao:_82690.csv',
 'Nome:_ARACAJU_Codigo_Estacao:_83096.csv',
 'Nome:_ITABAIANINHA_Codigo_Estacao:_83195.csv',
 'Nome:_PROPRIA_Codigo_Estacao:_83097.csv']

In [4]:
# dicionário para armazenar os DataFrames
dataframes = {}


# Loop para ler cada arquivo CSV e armazenar no dicionário
for arquivo in arquivos_csv:

    caminho_completo = os.path.join(diretorio, arquivo)

    #obtem o nome do arquivo sem a sua extensão e coloca na variável 'nome_df'
    nome_df = os.path.splitext(arquivo)[0]

    '''lê o dataframe pelo caminho do arquivo completo,delimitado por ponto e
    vírgula (CSV) e exclui da leitura as 10 primeiras linhas do arquivo
    com essa informação joga na variável 'dataframes[nome_df]'''
    dataframes[nome_df] = pd.read_csv(caminho_completo, delimiter=';', skiprows=10)

# 3° Separa os df de acordo com o tipo de index

In [5]:
# Função para verificar e classificar os índices dos DataFrames
def classificar_indices(dataframes):
    index_com_valores = []
    index_datatime = []
    index_numerico = []
    index_outro = []

    for nome, df in dataframes.items(): #nome: chave, df:valor
        if isinstance(df.index, pd.RangeIndex) and (df.index.start == 0 and df.index.stop == len(df) and df.index.step == 1):
            # Índice padrão do pandas (0, 1, 2, ...)
            index_numerico.append(nome)
        elif isinstance(df.index, pd.DatetimeIndex):
            # Índice do tipo datetime
            index_datatime.append(nome)
        elif not isinstance(df.index, pd.RangeIndex):
            # Índice não é numérico (não é o padrão do pandas)
            index_com_valores.append(nome)
        else:
            # Qualquer outro caso que não seja detectado acima
            index_outro.append(nome)

    return index_com_valores, index_numerico, index_outro, index_datatime

In [6]:
# Chamar a função para classificar os índices
index_com_valores, index_numerico, index_datatime, index_outro = classificar_indices(dataframes)

# Exibir os resultados
print("DataFrames com índice preenchido com algum valor:", index_com_valores)
print("DataFrames com índice numérico padrão do pandas:", index_numerico)
print("DataFrames com índice que não se encaixam em nenhum dos padrões acima:", index_outro)
print("DataFrames com índice com valor datatime:", index_datatime)

DataFrames com índice preenchido com algum valor: ['Nome:_AGUA_BRANCA_Codigo_Estacao:_82989', 'Nome:_ARAPIRACA_Codigo_Estacao:_82995', 'Nome:_MACEIO_Codigo_Estacao:_82994', 'Nome:_MAJOR_ISIDORO_Codigo_Estacao:_82991', 'Nome:_MATA_GRANDE_Codigo_Estacao:_82988', 'Nome:_PALMEIRA_DOS_INDIOS_Codigo_Estacao:_82992', 'Nome:_PAO_DE_ACUCAR_Codigo_Estacao:_82990', 'Nome:_PILAR_(MANGUABA)_Codigo_Estacao:_82998', 'Nome:_PORTO_DE_PEDRAS_Codigo_Estacao:_82996', 'Nome:_ALAGOINHAS_Codigo_Estacao:_83249', 'Nome:_BARRA_Codigo_Estacao:_83179', 'Nome:_CAETITE_Codigo_Estacao:_83339', 'Nome:_CAMACARI_Codigo_Estacao:_83226', 'Nome:_CANAVIEIRAS_Codigo_Estacao:_83398', 'Nome:_CARINHANHA_Codigo_Estacao:_83408', 'Nome:_CIPO_Codigo_Estacao:_83192', 'Nome:_CORRENTINA_Codigo_Estacao:_83286', 'Nome:_CRUZ_DAS_ALMAS_Codigo_Estacao:_83222', 'Nome:_FEIRA_DE_SANTANA_Codigo_Estacao:_83221', 'Nome:_GUARATINGA_Codigo_Estacao:_83446', 'Nome:_IRECE_Codigo_Estacao:_83182', 'Nome:_ITABERABA_Codigo_Estacao:_83244', 'Nome:_ITABUNA_Codigo_Estacao:_83347', 'Nome:_ITIRUCU_(JAGUAQUARA)_Codigo_Estacao:_83295', 'Nome:_ITUACU_Codigo_Estacao:_83292', 'Nome:_MONTE_SANTO_Codigo_Estacao:_83090', 'Nome:_MORRO_DO_CHAPEU_Codigo_Estacao:_83184', 'Nome:_MUCURI_Codigo_Estacao:_83549', 'Nome:_PAULO_AFONSO_Codigo_Estacao:_82986', 'Nome:_REMANSO_Codigo_Estacao:_82979', 'Nome:_SENHOR_DO_BONFIM_Codigo_Estacao:_83088', 'Nome:_SERRINHA_Codigo_Estacao:_83190', 'Nome:_STa._R._DE_CASSIA_(IBIPETUBA)_Codigo_Estacao:_83076', 'Nome:_ACARAU_Codigo_Estacao:_82294', 'Nome:_CAMPOS_SALES_Codigo_Estacao:_82777', 'Nome:_GUARAMIRANGA_Codigo_Estacao:_82487', 'Nome:_IGUATU_Codigo_Estacao:_82686', 'Nome:_JAGUARUANA_Codigo_Estacao:_82493', 'Nome:_JUAZEIRO_DO_NORTE_Codigo_Estacao:_82785', 'Nome:_MORADA_NOVA_Codigo_Estacao:_82588', 'Nome:_QUIXADA_Codigo_Estacao:_82486', 'Nome:_SOBRAL_Codigo_Estacao:_82392', 'Nome:_TAUA_Codigo_Estacao:_82683', 'Nome:_VICOSA_DO_CEARA_Codigo_Estacao:_82390', 'Nome:_ALTO_PARNAIBA_Codigo_Estacao:_82970', 'Nome:_BALSAS_Codigo_Estacao:_82768', 'Nome:_CAXIAS_Codigo_Estacao:_82476', 'Nome:_CHAPADINHA_Codigo_Estacao:_82382', 'Nome:_COLINAS_Codigo_Estacao:_82676', 'Nome:_IMPERATRIZ_Codigo_Estacao:_82564', 'Nome:_TURIACU_Codigo_Estacao:_82198', 'Nome:_ZE_DOCA_Codigo_Estacao:_82376', 'Nome:_AREIA_Codigo_Estacao:_82696', 'Nome:_CAMARATUBA_Codigo_Estacao:_82695', 'Nome:_CAMPINA_GRANDE_Codigo_Estacao:_82795', 'Nome:_GUARABIRA_Codigo_Estacao:_82697', 'Nome:_JOAO_PESSOA_Codigo_Estacao:_82798', 'Nome:_MONTEIRO_Codigo_Estacao:_82792', 'Nome:_SAO_GONCALO_Codigo_Estacao:_82689', 'Nome:_ARCO_VERDE_Codigo_Estacao:_82890', 'Nome:_CABROBO_Codigo_Estacao:_82886', 'Nome:_GARANHUNS_Codigo_Estacao:_82893', 'Nome:_GOIANA_Codigo_Estacao:_82799', 'Nome:_NAZARE_DA_MATA_Codigo_Estacao:_82781', 'Nome:_OLINDA_Codigo_Estacao:_82898', 'Nome:_OURICURI_Codigo_Estacao:_82753', 'Nome:_PESQUEIRA_Codigo_Estacao:_82892', 'Nome:_SURUBIM_Codigo_Estacao:_82797', 'Nome:_TAPACURA_Codigo_Estacao:_82897', 'Nome:_TRIUNFO_Codigo_Estacao:_82789', 'Nome:_ALTO_LONGA_(PILOTO_DO_LONGA)_Codigo_Estacao:_82605', 'Nome:_BOM_JESUS_DO_PIAUI_Codigo_Estacao:_82975', 'Nome:_CALDEIRAO_Codigo_Estacao:_82474', 'Nome:_CARACOL_Codigo_Estacao:_82976', 'Nome:_ESPERANTINA_Codigo_Estacao:_82298', 'Nome:_LUZILANDIA(LAG.DO_PIAUI)_Codigo_Estacao:_82296', 'Nome:_MORRO_DOS_CAVALOS_Codigo_Estacao:_82684', 'Nome:_PAULISTANA_Codigo_Estacao:_82882', 'Nome:_PICOS_Codigo_Estacao:_82780', 'Nome:_PIRIPIRI_Codigo_Estacao:_82480', 'Nome:_SAO_JOAO_DO_PIAUI_Codigo_Estacao:_82879', 'Nome:_VALE_DO_GURGUEIA_(CRISTIANO_CASTRO)_Codigo_Estacao:_82870', 'Nome:_APODI_Codigo_Estacao:_82590', 'Nome:_CEARA_MIRIM_Codigo_Estacao:_82596', 'Nome:_CRUZETA_Codigo_Estacao:_82693', 'Nome:_FLORANIA_Codigo_Estacao:_82691', 'Nome:_MACAIBA_Codigo_Estacao:_82597', 'Nome:_MACAU_Codigo_Estacao:_82594', 'Nome:_MOSSORO_Codigo_Estacao:_82591', 'Nome:_NOVA_CRUZ_Codigo_Estacao:_82698', 'Nome:_SERIDO_(CAICO)_Codigo_Estacao:_82690', 'Nome:_ITABAIANINHA_Codigo_Estacao:_83195', 'Nome:_PROPRIA_Codigo_Estacao:_83097']
DataFrames com índice numérico padrão do pandas: ['Nome:_BARREIRAS_Codigo_Estacao:_83236', 'Nome:_BOM_JESUS_DA_LAPA_Codigo_Estacao:_83288', 'Nome:_CARAVELAS_Codigo_Estacao:_83498', 'Nome:_JACOBINA_Codigo_Estacao:_83186', 'Nome:_LENCOIS_Codigo_Estacao:_83242', 'Nome:_SALVADOR_(ONDINA)_Codigo_Estacao:_83229', 'Nome:_VITORIA_DA_CONQUISTA_Codigo_Estacao:_83344', 'Nome:_BARBALHA_Codigo_Estacao:_82784', 'Nome:_CRATEUS_Codigo_Estacao:_82583', 'Nome:_FORTALEZA_Codigo_Estacao:_82397', 'Nome:_QUIXERAMOBIM_Codigo_Estacao:_82586', 'Nome:_BACABAL_Codigo_Estacao:_82460', 'Nome:_BARRA_DO_CORDA_Codigo_Estacao:_82571', 'Nome:_CAROLINA_Codigo_Estacao:_82765', 'Nome:_SAO_LUIS_Codigo_Estacao:_82280', 'Nome:_PATOS_Codigo_Estacao:_82791', 'Nome:_PETROLINA_Codigo_Estacao:_82983', 'Nome:_RECIFE_(CURADO)_Codigo_Estacao:_82900', 'Nome:_FLORIANO_Codigo_Estacao:_82678', 'Nome:_PARNAIBA_Codigo_Estacao:_82287', 'Nome:_TERESINA_Codigo_Estacao:_82578', 'Nome:_NATAL_Codigo_Estacao:_82598', 'Nome:_ARACAJU_Codigo_Estacao:_83096']
DataFrames com índice que não se encaixam em nenhum dos padrões acima: []
DataFrames com índice com valor datatime: []

In [7]:
#contanto a quantidade de elemento de cada lista
print("Quantidade de DataFrames com índice preenchido com algum valor:" + str(len(index_com_valores)))
print("Quantidade de DataFrames om índice numérico padrão do pandas:" + str(len(index_numerico)))

Quantidade de DataFrames com índice preenchido com algum valor:93
Quantidade de DataFrames om índice numérico padrão do pandas:23

# 4° DOIS TIPOS DE TRATAMENTOS PARA INDEX DIFERENTES

In [8]:
# Inicializar o dicionário para armazenar os DataFrames modificados
df_index_correto = {}

## Tratamento para indices preenchidos com algum valor

In [9]:
# Iterar sobre os nomes na lista 'index_com_valores'
for nome in index_com_valores:
    # Acessar o DataFrame correspondente no dicionário 'dataframes'
    df = dataframes[nome]
    # Converter o índice para datetime
    df.index = pd.to_datetime(df.index)
    # Adicionar o DataFrame modificado ao dicionário 'df_index_correto'
    df_index_correto[nome] = df

In [10]:
# exibir o nome de todos os df modificados nessa seção
for nome, df in df_index_correto.items():
    print(f"Nome do DataFrame: {nome}")

Nome do DataFrame: Nome:_AGUA_BRANCA_Codigo_Estacao:_82989
Nome do DataFrame: Nome:_ARAPIRACA_Codigo_Estacao:_82995
Nome do DataFrame: Nome:_MACEIO_Codigo_Estacao:_82994
Nome do DataFrame: Nome:_MAJOR_ISIDORO_Codigo_Estacao:_82991
Nome do DataFrame: Nome:_MATA_GRANDE_Codigo_Estacao:_82988
Nome do DataFrame: Nome:_PALMEIRA_DOS_INDIOS_Codigo_Estacao:_82992
Nome do DataFrame: Nome:_PAO_DE_ACUCAR_Codigo_Estacao:_82990
Nome do DataFrame: Nome:_PILAR_(MANGUABA)_Codigo_Estacao:_82998
Nome do DataFrame: Nome:_PORTO_DE_PEDRAS_Codigo_Estacao:_82996
Nome do DataFrame: Nome:_ALAGOINHAS_Codigo_Estacao:_83249
Nome do DataFrame: Nome:_BARRA_Codigo_Estacao:_83179
Nome do DataFrame: Nome:_CAETITE_Codigo_Estacao:_83339
Nome do DataFrame: Nome:_CAMACARI_Codigo_Estacao:_83226
Nome do DataFrame: Nome:_CANAVIEIRAS_Codigo_Estacao:_83398
Nome do DataFrame: Nome:_CARINHANHA_Codigo_Estacao:_83408
Nome do DataFrame: Nome:_CIPO_Codigo_Estacao:_83192
Nome do DataFrame: Nome:_CORRENTINA_Codigo_Estacao:_83286
Nome do DataFrame: Nome:_CRUZ_DAS_ALMAS_Codigo_Estacao:_83222
Nome do DataFrame: Nome:_FEIRA_DE_SANTANA_Codigo_Estacao:_83221
Nome do DataFrame: Nome:_GUARATINGA_Codigo_Estacao:_83446
Nome do DataFrame: Nome:_IRECE_Codigo_Estacao:_83182
Nome do DataFrame: Nome:_ITABERABA_Codigo_Estacao:_83244
Nome do DataFrame: Nome:_ITABUNA_Codigo_Estacao:_83347
Nome do DataFrame: Nome:_ITIRUCU_(JAGUAQUARA)_Codigo_Estacao:_83295
Nome do DataFrame: Nome:_ITUACU_Codigo_Estacao:_83292
Nome do DataFrame: Nome:_MONTE_SANTO_Codigo_Estacao:_83090
Nome do DataFrame: Nome:_MORRO_DO_CHAPEU_Codigo_Estacao:_83184
Nome do DataFrame: Nome:_MUCURI_Codigo_Estacao:_83549
Nome do DataFrame: Nome:_PAULO_AFONSO_Codigo_Estacao:_82986
Nome do DataFrame: Nome:_REMANSO_Codigo_Estacao:_82979
Nome do DataFrame: Nome:_SENHOR_DO_BONFIM_Codigo_Estacao:_83088
Nome do DataFrame: Nome:_SERRINHA_Codigo_Estacao:_83190
Nome do DataFrame: Nome:_STa._R._DE_CASSIA_(IBIPETUBA)_Codigo_Estacao:_83076
Nome do DataFrame: Nome:_ACARAU_Codigo_Estacao:_82294
Nome do DataFrame: Nome:_CAMPOS_SALES_Codigo_Estacao:_82777
Nome do DataFrame: Nome:_GUARAMIRANGA_Codigo_Estacao:_82487
Nome do DataFrame: Nome:_IGUATU_Codigo_Estacao:_82686
Nome do DataFrame: Nome:_JAGUARUANA_Codigo_Estacao:_82493
Nome do DataFrame: Nome:_JUAZEIRO_DO_NORTE_Codigo_Estacao:_82785
Nome do DataFrame: Nome:_MORADA_NOVA_Codigo_Estacao:_82588
Nome do DataFrame: Nome:_QUIXADA_Codigo_Estacao:_82486
Nome do DataFrame: Nome:_SOBRAL_Codigo_Estacao:_82392
Nome do DataFrame: Nome:_TAUA_Codigo_Estacao:_82683
Nome do DataFrame: Nome:_VICOSA_DO_CEARA_Codigo_Estacao:_82390
Nome do DataFrame: Nome:_ALTO_PARNAIBA_Codigo_Estacao:_82970
Nome do DataFrame: Nome:_BALSAS_Codigo_Estacao:_82768
Nome do DataFrame: Nome:_CAXIAS_Codigo_Estacao:_82476
Nome do DataFrame: Nome:_CHAPADINHA_Codigo_Estacao:_82382
Nome do DataFrame: Nome:_COLINAS_Codigo_Estacao:_82676
Nome do DataFrame: Nome:_IMPERATRIZ_Codigo_Estacao:_82564
Nome do DataFrame: Nome:_TURIACU_Codigo_Estacao:_82198
Nome do DataFrame: Nome:_ZE_DOCA_Codigo_Estacao:_82376
Nome do DataFrame: Nome:_AREIA_Codigo_Estacao:_82696
Nome do DataFrame: Nome:_CAMARATUBA_Codigo_Estacao:_82695
Nome do DataFrame: Nome:_CAMPINA_GRANDE_Codigo_Estacao:_82795
Nome do DataFrame: Nome:_GUARABIRA_Codigo_Estacao:_82697
Nome do DataFrame: Nome:_JOAO_PESSOA_Codigo_Estacao:_82798
Nome do DataFrame: Nome:_MONTEIRO_Codigo_Estacao:_82792
Nome do DataFrame: Nome:_SAO_GONCALO_Codigo_Estacao:_82689
Nome do DataFrame: Nome:_ARCO_VERDE_Codigo_Estacao:_82890
Nome do DataFrame: Nome:_CABROBO_Codigo_Estacao:_82886
Nome do DataFrame: Nome:_GARANHUNS_Codigo_Estacao:_82893
Nome do DataFrame: Nome:_GOIANA_Codigo_Estacao:_82799
Nome do DataFrame: Nome:_NAZARE_DA_MATA_Codigo_Estacao:_82781
Nome do DataFrame: Nome:_OLINDA_Codigo_Estacao:_82898
Nome do DataFrame: Nome:_OURICURI_Codigo_Estacao:_82753
Nome do DataFrame: Nome:_PESQUEIRA_Codigo_Estacao:_82892
Nome do DataFrame: Nome:_SURUBIM_Codigo_Estacao:_82797
Nome do DataFrame: Nome:_TAPACURA_Codigo_Estacao:_82897
Nome do DataFrame: Nome:_TRIUNFO_Codigo_Estacao:_82789
Nome do DataFrame: Nome:_ALTO_LONGA_(PILOTO_DO_LONGA)_Codigo_Estacao:_82605
Nome do DataFrame: Nome:_BOM_JESUS_DO_PIAUI_Codigo_Estacao:_82975
Nome do DataFrame: Nome:_CALDEIRAO_Codigo_Estacao:_82474
Nome do DataFrame: Nome:_CARACOL_Codigo_Estacao:_82976
Nome do DataFrame: Nome:_ESPERANTINA_Codigo_Estacao:_82298
Nome do DataFrame: Nome:_LUZILANDIA(LAG.DO_PIAUI)_Codigo_Estacao:_82296
Nome do DataFrame: Nome:_MORRO_DOS_CAVALOS_Codigo_Estacao:_82684
Nome do DataFrame: Nome:_PAULISTANA_Codigo_Estacao:_82882
Nome do DataFrame: Nome:_PICOS_Codigo_Estacao:_82780
Nome do DataFrame: Nome:_PIRIPIRI_Codigo_Estacao:_82480
Nome do DataFrame: Nome:_SAO_JOAO_DO_PIAUI_Codigo_Estacao:_82879
Nome do DataFrame: Nome:_VALE_DO_GURGUEIA_(CRISTIANO_CASTRO)_Codigo_Estacao:_82870
Nome do DataFrame: Nome:_APODI_Codigo_Estacao:_82590
Nome do DataFrame: Nome:_CEARA_MIRIM_Codigo_Estacao:_82596
Nome do DataFrame: Nome:_CRUZETA_Codigo_Estacao:_82693
Nome do DataFrame: Nome:_FLORANIA_Codigo_Estacao:_82691
Nome do DataFrame: Nome:_MACAIBA_Codigo_Estacao:_82597
Nome do DataFrame: Nome:_MACAU_Codigo_Estacao:_82594
Nome do DataFrame: Nome:_MOSSORO_Codigo_Estacao:_82591
Nome do DataFrame: Nome:_NOVA_CRUZ_Codigo_Estacao:_82698
Nome do DataFrame: Nome:_SERIDO_(CAICO)_Codigo_Estacao:_82690
Nome do DataFrame: Nome:_ITABAIANINHA_Codigo_Estacao:_83195
Nome do DataFrame: Nome:_PROPRIA_Codigo_Estacao:_83097

In [11]:
#verificando o tipo de index de um df aleatório
ex1 = df_index_correto['Nome:_CORRENTINA_Codigo_Estacao:_83286']
type(ex1.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [12]:
#verificando se o tamanho condiz com o tamanho da lista de df que precisava desse tratamento
len(df_index_correto)

93

## Tratamento para indices com valores numéricos de 0 a n

In [13]:
ex2 = dataframes['Nome:_BARREIRAS_Codigo_Estacao:_83236']
ex2

,Data Medicao,"DIRECAO PREDOMINANTE DO VENTO, MENSAL(° (gr))","EVAPORACAO DO PICHE, MENSAL(mm)","EVAPOTRANSPIRACAO POTENCIAL, BH MENSAL(mm)","EVAPOTRANSPIRACAO REAL, BH MENSAL(mm)","INSOLACAO TOTAL, MENSAL(h)","NEBULOSIDADE, MEDIA MENSAL(décimos)","NUMERO DE DIAS COM PRECIP. PLUV, MENSAL(número)","PRECIPITACAO TOTAL, MENSAL(mm)","PRESSAO ATMOSFERICA AO NIVEL DO MAR, MEDIA MENSAL(mB)","PRESSAO ATMOSFERICA, MEDIA MENSAL(mB)","TEMPERATURA MAXIMA MEDIA, MENSAL(°C)","TEMPERATURA MEDIA COMPENSADA, MENSAL(°C)","TEMPERATURA MINIMA MEDIA, MENSAL(°C)","UMIDADE RELATIVA DO AR, MEDIA MENSAL(%)","VENTO, VELOCIDADE MAXIMA MENSAL(m/s)","VENTO, VELOCIDADE MEDIA MENSAL(m/s)","VISIBILIDADE, MEDIA MENSAL(codigo)",Unnamed: 18
0,2000-01-31,0.0,"88,1",NaN,NaN,NaN,"7,5",15.0,"183,9",NaN,"959,5","30,5","24,8","20,8","81,3","6,5",",9","64,4",NaN
1,2000-02-29,0.0,69,NaN,NaN,NaN,"7,4",14.0,"248,4",NaN,"961,3","30,5","24,7",21,"80,6","4,8",1,66,NaN
2,2000-03-31,0.0,"83,8",NaN,NaN,NaN,"6,4",12.0,"93,9",NaN,"960,1","30,2","24,6","20,8",80,"7,3","1,2","68,6",NaN
3,2000-04-30,0.0,88,NaN,NaN,NaN,"6,4",11.0,"73,5",NaN,"961,3","31,2","24,6","20,5","78,5","4,3",1,"71,5",NaN
4,2000-05-31,0.0,"123,2",NaN,NaN,NaN,"4,4",2.0,"9,9",NaN,"962,6","31,8","23,3","17,6","72,3","3,3",",9","73,7",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,2024-02-29,0.0,NaN,NaN,NaN,"176,7",6,13.0,"328,1","1011,7","962,9","32,2","25,8",21,NaN,"3,1",",4","97,9",NaN
290,2024-03-31,0.0,NaN,NaN,NaN,"271,7","4,2",5.0,42,"1010,3","961,9","34,5","27,2","21,1",NaN,"4,1",",4",98,NaN
291,2024-04-30,0.0,NaN,NaN,NaN,224,"4,6",11.0,"102,9","1010,8","962,3","33,2","26,4","21,4",NaN,"3,1",",6",98,NaN
292,2024-05-31,0.0,NaN,NaN,NaN,"299,5",2,0.0,0,"1012,8","963,7","33,5","24,5","17,1",NaN,"3,6",",7",98,NaN
293,2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,6",NaN,NaN,NaN

In [14]:
ex2.dtypes

Data Medicao                                              object
DIRECAO PREDOMINANTE DO VENTO, MENSAL(° (gr))            float64
EVAPORACAO DO PICHE, MENSAL(mm)                           object
EVAPOTRANSPIRACAO POTENCIAL, BH MENSAL(mm)                object
EVAPOTRANSPIRACAO REAL, BH MENSAL(mm)                     object
INSOLACAO TOTAL, MENSAL(h)                                object
NEBULOSIDADE, MEDIA MENSAL(décimos)                       object
NUMERO DE DIAS COM PRECIP. PLUV, MENSAL(número)          float64
PRECIPITACAO TOTAL, MENSAL(mm)                            object
PRESSAO ATMOSFERICA AO NIVEL DO MAR, MEDIA MENSAL(mB)     object
PRESSAO ATMOSFERICA, MEDIA MENSAL(mB)                     object
TEMPERATURA MAXIMA MEDIA, MENSAL(°C)                      object
TEMPERATURA MEDIA COMPENSADA, MENSAL(°C)                  object
TEMPERATURA MINIMA MEDIA, MENSAL(°C)                      object
UMIDADE RELATIVA DO AR, MEDIA MENSAL(%)                   object
VENTO, VELOCIDADE MAXIMA MENSAL(m/s)                      object
VENTO, VELOCIDADE MEDIA MENSAL(m/s)                       object
VISIBILIDADE, MEDIA MENSAL(codigo)                        object
Unnamed: 18                                              float64
dtype: object

In [15]:
# Iterar sobre os nomes na lista 'index_numerico'
for nome in index_numerico:
    # Acessar o DataFrame correspondente no dicionário 'dataframes'
    df = dataframes[nome]
    # Converter a coluna Data medição para tipo datatime
    df['Data Medicao'] = pd.to_datetime(df['Data Medicao'])
    # Definir a coluna Data medição como índice
    df.set_index('Data Medicao', inplace=True)
    # Adicionar o DataFrame modificado ao dicionário 'df_index_correto'
    df_index_correto[nome] = df

In [16]:
# exibir o exemplo de df de uma estação de novo
ex2

,"DIRECAO PREDOMINANTE DO VENTO, MENSAL(° (gr))","EVAPORACAO DO PICHE, MENSAL(mm)","EVAPOTRANSPIRACAO POTENCIAL, BH MENSAL(mm)","EVAPOTRANSPIRACAO REAL, BH MENSAL(mm)","INSOLACAO TOTAL, MENSAL(h)","NEBULOSIDADE, MEDIA MENSAL(décimos)","NUMERO DE DIAS COM PRECIP. PLUV, MENSAL(número)","PRECIPITACAO TOTAL, MENSAL(mm)","PRESSAO ATMOSFERICA AO NIVEL DO MAR, MEDIA MENSAL(mB)","PRESSAO ATMOSFERICA, MEDIA MENSAL(mB)","TEMPERATURA MAXIMA MEDIA, MENSAL(°C)","TEMPERATURA MEDIA COMPENSADA, MENSAL(°C)","TEMPERATURA MINIMA MEDIA, MENSAL(°C)","UMIDADE RELATIVA DO AR, MEDIA MENSAL(%)","VENTO, VELOCIDADE MAXIMA MENSAL(m/s)","VENTO, VELOCIDADE MEDIA MENSAL(m/s)","VISIBILIDADE, MEDIA MENSAL(codigo)",Unnamed: 18
Data Medicao,,,,,,,,,,,,,,,,,,
2000-01-31,0.0,"88,1",NaN,NaN,NaN,"7,5",15.0,"183,9",NaN,"959,5","30,5","24,8","20,8","81,3","6,5",",9","64,4",NaN
2000-02-29,0.0,69,NaN,NaN,NaN,"7,4",14.0,"248,4",NaN,"961,3","30,5","24,7",21,"80,6","4,8",1,66,NaN
2000-03-31,0.0,"83,8",NaN,NaN,NaN,"6,4",12.0,"93,9",NaN,"960,1","30,2","24,6","20,8",80,"7,3","1,2","68,6",NaN
2000-04-30,0.0,88,NaN,NaN,NaN,"6,4",11.0,"73,5",NaN,"961,3","31,2","24,6","20,5","78,5","4,3",1,"71,5",NaN
2000-05-31,0.0,"123,2",NaN,NaN,NaN,"4,4",2.0,"9,9",NaN,"962,6","31,8","23,3","17,6","72,3","3,3",",9","73,7",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-02-29,0.0,NaN,NaN,NaN,"176,7",6,13.0,"328,1","1011,7","962,9","32,2","25,8",21,NaN,"3,1",",4","97,9",NaN
2024-03-31,0.0,NaN,NaN,NaN,"271,7","4,2",5.0,42,"1010,3","961,9","34,5","27,2","21,1",NaN,"4,1",",4",98,NaN
2024-04-30,0.0,NaN,NaN,NaN,224,"4,6",11.0,"102,9","1010,8","962,3","33,2","26,4","21,4",NaN,"3,1",",6",98,NaN
2024-05-31,0.0,NaN,NaN,NaN,"299,5",2,0.0,0,"1012,8","963,7","33,5","24,5","17,1",NaN,"3,6",",7",98,NaN
2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,6",NaN,NaN,NaN

In [17]:
# exibir o tipo do index
type(ex2.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [18]:
#conferir o tamanho do dicionário
len(df_index_correto)

116

# 5° Transformação em série temporal

In [19]:
#colunas que eu quero nas minhas séries
colunas_interesse = ['PRECIPITACAO TOTAL, MENSAL(mm)', 'INSOLACAO TOTAL, MENSAL(h)', 'VENTO, VELOCIDADE MEDIA MENSAL(m/s)']

# Dicionário para armazenar as séries temporais
series_temp = {}

# Loop sobre cada DataFrame no dicionário original
for nome, df in df_index_correto.items():
    # Selecionar e copiar as colunas de interesse
    df_copia = df[colunas_interesse].copy()

    # Converter as colunas para o tipo float
    for coluna in colunas_interesse:
        df_copia[coluna] = df_copia[coluna].astype(str).str.replace(',', '.')
        df_copia[coluna] = df_copia[coluna].astype(float)

    # Adicionar o DataFrame copiado ao dicionário de séries temporais
    series_temp[nome] = df_copia

# 6° LIMPEZA

In [20]:
# Inicializar o novo dicionário para armazenar as séries limpas
series_limp = {}

# Loop sobre cada série temporal no dicionário original
for nome, df in series_temp.items():
    # Substituir 'null' (ou 'None') por 'NaN'
    df = df.replace({None: np.nan})

    # Remover as linhas que têm qualquer valor de NaN
    df_limpo = df.dropna()

    # Adicionar o DataFrame limpo ao dicionário 'series_limp'
    series_limp[nome] = df_limpo

# Agora 'series_limp' contém as séries temporais limpas

In [21]:
# Inicializar uma lista para armazenar o nome das séries que ainda contêm NaN
series_com_nan = []

# Iterar sobre cada série no dicionário 'series_limp'
for nome, df in series_limp.items():
    # Verificar se há algum NaN no DataFrame
    if df.isna().any().any():
        # Se houver NaN, adicionar o nome da série à lista
        series_com_nan.append(nome)

# Exibir a lista de séries que ainda contêm valores NaN
print("Séries com valores NaN restantes:", series_com_nan)

Séries com valores NaN restantes: []

# 7° Guardar as séries limpas em arquivos CSVs

In [22]:
# Diretório onde os arquivos CSV serão salvos, no meu google drive
diretorio_saida = '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS'

# Iterar sobre cada série no dicionário 'series_limp'
for nome, df in series_limp.items():
    # Criar o caminho completo para o arquivo CSV
    caminho_arquivo = os.path.join(diretorio_saida, f"{nome}.csv")

    # Salvar o DataFrame como um arquivo CSV
    df.to_csv(caminho_arquivo)

    # Exibir uma mensagem de confirmação (opcional)
    print(f"Série temporal '{nome}' foi salva em '{caminho_arquivo}'")

Série temporal 'Nome:_AGUA_BRANCA_Codigo_Estacao:_82989' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_AGUA_BRANCA_Codigo_Estacao:_82989.csv'
Série temporal 'Nome:_ARAPIRACA_Codigo_Estacao:_82995' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ARAPIRACA_Codigo_Estacao:_82995.csv'
Série temporal 'Nome:_MACEIO_Codigo_Estacao:_82994' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MACEIO_Codigo_Estacao:_82994.csv'
Série temporal 'Nome:_MAJOR_ISIDORO_Codigo_Estacao:_82991' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MAJOR_ISIDORO_Codigo_Estacao:_82991.csv'
Série temporal 'Nome:_MATA_GRANDE_Codigo_Estacao:_82988' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MATA_GRANDE_Codigo_Estacao:_82988.csv'
Série temporal 'Nome:_PALMEIRA_DOS_INDIOS_Codigo_Estacao:_82992' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PALMEIRA_DOS_INDIOS_Codigo_Estacao:_82992.csv'
Série temporal 'Nome:_PAO_DE_ACUCAR_Codigo_Estacao:_82990' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PAO_DE_ACUCAR_Codigo_Estacao:_82990.csv'
Série temporal 'Nome:_PILAR_(MANGUABA)_Codigo_Estacao:_82998' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PILAR_(MANGUABA)_Codigo_Estacao:_82998.csv'
Série temporal 'Nome:_PORTO_DE_PEDRAS_Codigo_Estacao:_82996' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PORTO_DE_PEDRAS_Codigo_Estacao:_82996.csv'
Série temporal 'Nome:_ALAGOINHAS_Codigo_Estacao:_83249' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ALAGOINHAS_Codigo_Estacao:_83249.csv'
Série temporal 'Nome:_BARRA_Codigo_Estacao:_83179' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BARRA_Codigo_Estacao:_83179.csv'
Série temporal 'Nome:_CAETITE_Codigo_Estacao:_83339' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CAETITE_Codigo_Estacao:_83339.csv'
Série temporal 'Nome:_CAMACARI_Codigo_Estacao:_83226' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CAMACARI_Codigo_Estacao:_83226.csv'
Série temporal 'Nome:_CANAVIEIRAS_Codigo_Estacao:_83398' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CANAVIEIRAS_Codigo_Estacao:_83398.csv'
Série temporal 'Nome:_CARINHANHA_Codigo_Estacao:_83408' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CARINHANHA_Codigo_Estacao:_83408.csv'
Série temporal 'Nome:_CIPO_Codigo_Estacao:_83192' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CIPO_Codigo_Estacao:_83192.csv'
Série temporal 'Nome:_CORRENTINA_Codigo_Estacao:_83286' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CORRENTINA_Codigo_Estacao:_83286.csv'
Série temporal 'Nome:_CRUZ_DAS_ALMAS_Codigo_Estacao:_83222' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CRUZ_DAS_ALMAS_Codigo_Estacao:_83222.csv'
Série temporal 'Nome:_FEIRA_DE_SANTANA_Codigo_Estacao:_83221' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_FEIRA_DE_SANTANA_Codigo_Estacao:_83221.csv'
Série temporal 'Nome:_GUARATINGA_Codigo_Estacao:_83446' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_GUARATINGA_Codigo_Estacao:_83446.csv'
Série temporal 'Nome:_IRECE_Codigo_Estacao:_83182' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_IRECE_Codigo_Estacao:_83182.csv'
Série temporal 'Nome:_ITABERABA_Codigo_Estacao:_83244' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ITABERABA_Codigo_Estacao:_83244.csv'
Série temporal 'Nome:_ITABUNA_Codigo_Estacao:_83347' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ITABUNA_Codigo_Estacao:_83347.csv'
Série temporal 'Nome:_ITIRUCU_(JAGUAQUARA)_Codigo_Estacao:_83295' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ITIRUCU_(JAGUAQUARA)_Codigo_Estacao:_83295.csv'
Série temporal 'Nome:_ITUACU_Codigo_Estacao:_83292' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ITUACU_Codigo_Estacao:_83292.csv'
Série temporal 'Nome:_MONTE_SANTO_Codigo_Estacao:_83090' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MONTE_SANTO_Codigo_Estacao:_83090.csv'
Série temporal 'Nome:_MORRO_DO_CHAPEU_Codigo_Estacao:_83184' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MORRO_DO_CHAPEU_Codigo_Estacao:_83184.csv'
Série temporal 'Nome:_MUCURI_Codigo_Estacao:_83549' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MUCURI_Codigo_Estacao:_83549.csv'
Série temporal 'Nome:_PAULO_AFONSO_Codigo_Estacao:_82986' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PAULO_AFONSO_Codigo_Estacao:_82986.csv'
Série temporal 'Nome:_REMANSO_Codigo_Estacao:_82979' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_REMANSO_Codigo_Estacao:_82979.csv'
Série temporal 'Nome:_SENHOR_DO_BONFIM_Codigo_Estacao:_83088' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SENHOR_DO_BONFIM_Codigo_Estacao:_83088.csv'
Série temporal 'Nome:_SERRINHA_Codigo_Estacao:_83190' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SERRINHA_Codigo_Estacao:_83190.csv'
Série temporal 'Nome:_STa._R._DE_CASSIA_(IBIPETUBA)_Codigo_Estacao:_83076' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_STa._R._DE_CASSIA_(IBIPETUBA)_Codigo_Estacao:_83076.csv'
Série temporal 'Nome:_ACARAU_Codigo_Estacao:_82294' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ACARAU_Codigo_Estacao:_82294.csv'
Série temporal 'Nome:_CAMPOS_SALES_Codigo_Estacao:_82777' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CAMPOS_SALES_Codigo_Estacao:_82777.csv'
Série temporal 'Nome:_GUARAMIRANGA_Codigo_Estacao:_82487' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_GUARAMIRANGA_Codigo_Estacao:_82487.csv'
Série temporal 'Nome:_IGUATU_Codigo_Estacao:_82686' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_IGUATU_Codigo_Estacao:_82686.csv'
Série temporal 'Nome:_JAGUARUANA_Codigo_Estacao:_82493' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_JAGUARUANA_Codigo_Estacao:_82493.csv'
Série temporal 'Nome:_JUAZEIRO_DO_NORTE_Codigo_Estacao:_82785' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_JUAZEIRO_DO_NORTE_Codigo_Estacao:_82785.csv'
Série temporal 'Nome:_MORADA_NOVA_Codigo_Estacao:_82588' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MORADA_NOVA_Codigo_Estacao:_82588.csv'
Série temporal 'Nome:_QUIXADA_Codigo_Estacao:_82486' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_QUIXADA_Codigo_Estacao:_82486.csv'
Série temporal 'Nome:_SOBRAL_Codigo_Estacao:_82392' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SOBRAL_Codigo_Estacao:_82392.csv'
Série temporal 'Nome:_TAUA_Codigo_Estacao:_82683' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_TAUA_Codigo_Estacao:_82683.csv'
Série temporal 'Nome:_VICOSA_DO_CEARA_Codigo_Estacao:_82390' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_VICOSA_DO_CEARA_Codigo_Estacao:_82390.csv'
Série temporal 'Nome:_ALTO_PARNAIBA_Codigo_Estacao:_82970' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ALTO_PARNAIBA_Codigo_Estacao:_82970.csv'
Série temporal 'Nome:_BALSAS_Codigo_Estacao:_82768' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BALSAS_Codigo_Estacao:_82768.csv'
Série temporal 'Nome:_CAXIAS_Codigo_Estacao:_82476' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CAXIAS_Codigo_Estacao:_82476.csv'
Série temporal 'Nome:_CHAPADINHA_Codigo_Estacao:_82382' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CHAPADINHA_Codigo_Estacao:_82382.csv'
Série temporal 'Nome:_COLINAS_Codigo_Estacao:_82676' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_COLINAS_Codigo_Estacao:_82676.csv'
Série temporal 'Nome:_IMPERATRIZ_Codigo_Estacao:_82564' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_IMPERATRIZ_Codigo_Estacao:_82564.csv'
Série temporal 'Nome:_TURIACU_Codigo_Estacao:_82198' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_TURIACU_Codigo_Estacao:_82198.csv'
Série temporal 'Nome:_ZE_DOCA_Codigo_Estacao:_82376' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ZE_DOCA_Codigo_Estacao:_82376.csv'
Série temporal 'Nome:_AREIA_Codigo_Estacao:_82696' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_AREIA_Codigo_Estacao:_82696.csv'
Série temporal 'Nome:_CAMARATUBA_Codigo_Estacao:_82695' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CAMARATUBA_Codigo_Estacao:_82695.csv'
Série temporal 'Nome:_CAMPINA_GRANDE_Codigo_Estacao:_82795' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CAMPINA_GRANDE_Codigo_Estacao:_82795.csv'
Série temporal 'Nome:_GUARABIRA_Codigo_Estacao:_82697' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_GUARABIRA_Codigo_Estacao:_82697.csv'
Série temporal 'Nome:_JOAO_PESSOA_Codigo_Estacao:_82798' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_JOAO_PESSOA_Codigo_Estacao:_82798.csv'
Série temporal 'Nome:_MONTEIRO_Codigo_Estacao:_82792' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MONTEIRO_Codigo_Estacao:_82792.csv'
Série temporal 'Nome:_SAO_GONCALO_Codigo_Estacao:_82689' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SAO_GONCALO_Codigo_Estacao:_82689.csv'
Série temporal 'Nome:_ARCO_VERDE_Codigo_Estacao:_82890' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ARCO_VERDE_Codigo_Estacao:_82890.csv'
Série temporal 'Nome:_CABROBO_Codigo_Estacao:_82886' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CABROBO_Codigo_Estacao:_82886.csv'
Série temporal 'Nome:_GARANHUNS_Codigo_Estacao:_82893' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_GARANHUNS_Codigo_Estacao:_82893.csv'
Série temporal 'Nome:_GOIANA_Codigo_Estacao:_82799' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_GOIANA_Codigo_Estacao:_82799.csv'
Série temporal 'Nome:_NAZARE_DA_MATA_Codigo_Estacao:_82781' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_NAZARE_DA_MATA_Codigo_Estacao:_82781.csv'
Série temporal 'Nome:_OLINDA_Codigo_Estacao:_82898' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_OLINDA_Codigo_Estacao:_82898.csv'
Série temporal 'Nome:_OURICURI_Codigo_Estacao:_82753' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_OURICURI_Codigo_Estacao:_82753.csv'
Série temporal 'Nome:_PESQUEIRA_Codigo_Estacao:_82892' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PESQUEIRA_Codigo_Estacao:_82892.csv'
Série temporal 'Nome:_SURUBIM_Codigo_Estacao:_82797' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SURUBIM_Codigo_Estacao:_82797.csv'
Série temporal 'Nome:_TAPACURA_Codigo_Estacao:_82897' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_TAPACURA_Codigo_Estacao:_82897.csv'
Série temporal 'Nome:_TRIUNFO_Codigo_Estacao:_82789' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_TRIUNFO_Codigo_Estacao:_82789.csv'
Série temporal 'Nome:_ALTO_LONGA_(PILOTO_DO_LONGA)_Codigo_Estacao:_82605' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ALTO_LONGA_(PILOTO_DO_LONGA)_Codigo_Estacao:_82605.csv'
Série temporal 'Nome:_BOM_JESUS_DO_PIAUI_Codigo_Estacao:_82975' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BOM_JESUS_DO_PIAUI_Codigo_Estacao:_82975.csv'
Série temporal 'Nome:_CALDEIRAO_Codigo_Estacao:_82474' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CALDEIRAO_Codigo_Estacao:_82474.csv'
Série temporal 'Nome:_CARACOL_Codigo_Estacao:_82976' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CARACOL_Codigo_Estacao:_82976.csv'
Série temporal 'Nome:_ESPERANTINA_Codigo_Estacao:_82298' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ESPERANTINA_Codigo_Estacao:_82298.csv'
Série temporal 'Nome:_LUZILANDIA(LAG.DO_PIAUI)_Codigo_Estacao:_82296' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_LUZILANDIA(LAG.DO_PIAUI)_Codigo_Estacao:_82296.csv'
Série temporal 'Nome:_MORRO_DOS_CAVALOS_Codigo_Estacao:_82684' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MORRO_DOS_CAVALOS_Codigo_Estacao:_82684.csv'
Série temporal 'Nome:_PAULISTANA_Codigo_Estacao:_82882' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PAULISTANA_Codigo_Estacao:_82882.csv'
Série temporal 'Nome:_PICOS_Codigo_Estacao:_82780' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PICOS_Codigo_Estacao:_82780.csv'
Série temporal 'Nome:_PIRIPIRI_Codigo_Estacao:_82480' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PIRIPIRI_Codigo_Estacao:_82480.csv'
Série temporal 'Nome:_SAO_JOAO_DO_PIAUI_Codigo_Estacao:_82879' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SAO_JOAO_DO_PIAUI_Codigo_Estacao:_82879.csv'
Série temporal 'Nome:_VALE_DO_GURGUEIA_(CRISTIANO_CASTRO)_Codigo_Estacao:_82870' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_VALE_DO_GURGUEIA_(CRISTIANO_CASTRO)_Codigo_Estacao:_82870.csv'
Série temporal 'Nome:_APODI_Codigo_Estacao:_82590' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_APODI_Codigo_Estacao:_82590.csv'
Série temporal 'Nome:_CEARA_MIRIM_Codigo_Estacao:_82596' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CEARA_MIRIM_Codigo_Estacao:_82596.csv'
Série temporal 'Nome:_CRUZETA_Codigo_Estacao:_82693' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CRUZETA_Codigo_Estacao:_82693.csv'
Série temporal 'Nome:_FLORANIA_Codigo_Estacao:_82691' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_FLORANIA_Codigo_Estacao:_82691.csv'
Série temporal 'Nome:_MACAIBA_Codigo_Estacao:_82597' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MACAIBA_Codigo_Estacao:_82597.csv'
Série temporal 'Nome:_MACAU_Codigo_Estacao:_82594' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MACAU_Codigo_Estacao:_82594.csv'
Série temporal 'Nome:_MOSSORO_Codigo_Estacao:_82591' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_MOSSORO_Codigo_Estacao:_82591.csv'
Série temporal 'Nome:_NOVA_CRUZ_Codigo_Estacao:_82698' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_NOVA_CRUZ_Codigo_Estacao:_82698.csv'
Série temporal 'Nome:_SERIDO_(CAICO)_Codigo_Estacao:_82690' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SERIDO_(CAICO)_Codigo_Estacao:_82690.csv'
Série temporal 'Nome:_ITABAIANINHA_Codigo_Estacao:_83195' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ITABAIANINHA_Codigo_Estacao:_83195.csv'
Série temporal 'Nome:_PROPRIA_Codigo_Estacao:_83097' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PROPRIA_Codigo_Estacao:_83097.csv'
Série temporal 'Nome:_BARREIRAS_Codigo_Estacao:_83236' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BARREIRAS_Codigo_Estacao:_83236.csv'
Série temporal 'Nome:_BOM_JESUS_DA_LAPA_Codigo_Estacao:_83288' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BOM_JESUS_DA_LAPA_Codigo_Estacao:_83288.csv'
Série temporal 'Nome:_CARAVELAS_Codigo_Estacao:_83498' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CARAVELAS_Codigo_Estacao:_83498.csv'
Série temporal 'Nome:_JACOBINA_Codigo_Estacao:_83186' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_JACOBINA_Codigo_Estacao:_83186.csv'
Série temporal 'Nome:_LENCOIS_Codigo_Estacao:_83242' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_LENCOIS_Codigo_Estacao:_83242.csv'
Série temporal 'Nome:_SALVADOR_(ONDINA)_Codigo_Estacao:_83229' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SALVADOR_(ONDINA)_Codigo_Estacao:_83229.csv'
Série temporal 'Nome:_VITORIA_DA_CONQUISTA_Codigo_Estacao:_83344' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_VITORIA_DA_CONQUISTA_Codigo_Estacao:_83344.csv'
Série temporal 'Nome:_BARBALHA_Codigo_Estacao:_82784' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BARBALHA_Codigo_Estacao:_82784.csv'
Série temporal 'Nome:_CRATEUS_Codigo_Estacao:_82583' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CRATEUS_Codigo_Estacao:_82583.csv'
Série temporal 'Nome:_FORTALEZA_Codigo_Estacao:_82397' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_FORTALEZA_Codigo_Estacao:_82397.csv'
Série temporal 'Nome:_QUIXERAMOBIM_Codigo_Estacao:_82586' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_QUIXERAMOBIM_Codigo_Estacao:_82586.csv'
Série temporal 'Nome:_BACABAL_Codigo_Estacao:_82460' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BACABAL_Codigo_Estacao:_82460.csv'
Série temporal 'Nome:_BARRA_DO_CORDA_Codigo_Estacao:_82571' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_BARRA_DO_CORDA_Codigo_Estacao:_82571.csv'
Série temporal 'Nome:_CAROLINA_Codigo_Estacao:_82765' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_CAROLINA_Codigo_Estacao:_82765.csv'
Série temporal 'Nome:_SAO_LUIS_Codigo_Estacao:_82280' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_SAO_LUIS_Codigo_Estacao:_82280.csv'
Série temporal 'Nome:_PATOS_Codigo_Estacao:_82791' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PATOS_Codigo_Estacao:_82791.csv'
Série temporal 'Nome:_PETROLINA_Codigo_Estacao:_82983' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PETROLINA_Codigo_Estacao:_82983.csv'
Série temporal 'Nome:_RECIFE_(CURADO)_Codigo_Estacao:_82900' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_RECIFE_(CURADO)_Codigo_Estacao:_82900.csv'
Série temporal 'Nome:_FLORIANO_Codigo_Estacao:_82678' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_FLORIANO_Codigo_Estacao:_82678.csv'
Série temporal 'Nome:_PARNAIBA_Codigo_Estacao:_82287' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_PARNAIBA_Codigo_Estacao:_82287.csv'
Série temporal 'Nome:_TERESINA_Codigo_Estacao:_82578' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_TERESINA_Codigo_Estacao:_82578.csv'
Série temporal 'Nome:_NATAL_Codigo_Estacao:_82598' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_NATAL_Codigo_Estacao:_82598.csv'
Série temporal 'Nome:_ARACAJU_Codigo_Estacao:_83096' foi salva em '/content/drive/MyDrive/TCC/DADOS/SERIES_TEMP_LIMPAS/Nome:_ARACAJU_Codigo_Estacao:_83096.csv'

# 8° Leitura das 9 primeiras linhas de cada CSV e guardar as informações em um novo DF, pra posteriormente salvar em um arquivo CSV

In [29]:
# Caminho onde estão os arquivos CSV
caminho_dos_arquivos = '/content/drive/MyDrive/TCC/DADOS/CONVENCIONAL'

# Inicializando uma lista para armazenar os dados de cada subestação
dados_subestacoes = []

# Lista de arquivos no diretório
arquivos = [f for f in os.listdir(caminho_dos_arquivos) if f.endswith('.csv')]

# Iterando sobre cada arquivo
for arquivo in arquivos_csv:
    caminho_arquivo = os.path.join(caminho_dos_arquivos, arquivo)

    # Lendo as primeiras 9 linhas do arquivo
    with open(caminho_arquivo, 'r') as f:
        linhas = [f.readline().strip() for _ in range(9)]

    # Extraindo a informação antes e depois do ":"
    info_dict = {}
    for linha in linhas:
        chave, valor = linha.split(':', 1)
        chave = chave.strip()
        valor = valor.strip()
        info_dict[chave] = valor

    # Adicionando o dicionário às listas de dados
    dados_subestacoes.append(info_dict)

# Criando o DataFrame a partir da lista de dicionários
est_info = pd.DataFrame(dados_subestacoes)

# Exibindo o DataFrame resultante
est_info.head()

,Nome,Codigo Estacao,Latitude,Longitude,Altitude,Situacao,Data Inicial,Data Final,Periodicidade da Medicao
0,AGUA BRANCA,82989,-9.26472222,-37.93805555,603.42,Operante,2000-01-01,2024-06-01,Mensal
1,ARAPIRACA,82995,-9.73,-36.77,247,Desativada,2000-01-01,2024-06-01,Mensal
2,MACEIO,82994,-9.55138888,-35.77083332,84.12,Fechada,2000-01-01,2021-04-07,Mensal
3,MAJOR ISIDORO,82991,-9.55,-37.02,200,Desativada,2000-01-01,2024-06-01,Mensal
4,MATA GRANDE,82988,-9.12,-37.73,635,Desativada,2000-01-01,2024-06-01,Mensal

In [30]:
#veriificando se foram os 116 arquivos de CSVs
len(est_info)

116

In [31]:
#verificando o tipo de cada coluna
est_info.dtypes

Nome                        object
Codigo Estacao              object
Latitude                    object
Longitude                   object
Altitude                    object
Situacao                    object
Data Inicial                object
Data Final                  object
Periodicidade da Medicao    object
dtype: object

In [32]:
# Especificar o caminho onde o arquivo CSV será salvo
caminho_est_info = '/content/drive/MyDrive/TCC/DADOS/INFORMACOES_ESTACOES/informacoes_estacoes.csv'

# Salvar o DataFrame em um arquivo CSV
est_info.to_csv(caminho_est_info, index=False)